# Generated by Django 5.2 on 2025-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
